= Armies

// Exclude from PDF output (show only in HTML output).
ifndef::loader-assembler[]
_Version: {revnumber} | Date of this build: {docdate}_
endif::[]

// Frontmatter to show only in PDF output.
ifdef::loader-assembler[]
// Colophon: Show only in PDF output.
[preface]
include::home::partial$colophon.adoc[]
endif::[]

// Table of contents: Not relevant for HTML output. Make sure that this code is *after* all content that we want to treat as frontmatter in the PDF output.
ifdef::loader-assembler[]
include::home::partial$toc.adoc[]
endif::[]

[discrete]
== The army lists

Here you'll find guidance on how to choose and build your armies for {project-name}.
You'll also find army lists that detail detachments, unit data sheets and points costs for each faction in the game.

.Under development
****
You can find the latest developments on the Remastered army lists in our detachment builder at link:https://builder.epicremastered.com[^].
(We intend to mirror the builder content here too, in due course.)

You can also find the original {e40k} army lists at link:https://thehobby.zone/resources/e40k-compendium/Content/Armies/Armies.htm[^].
And you can find related 'lore' at link:https://thehobby.zone/resources/e40k-compendium/Content/Lore/Lore.htm[^].
****